# PATH TO ALL DATA
data_dir: exported_data

# CONNECTING TO A DATABASE
adapter: mysql2
host: localhost
database: drupal_database_name
user: username
password: secret_password

# DRUPAL SETTINGS
drupal_content_types_json: drupal_settings/drupal_content_types.json
drupal_boolean_columns: drupal_settings/boolean_columns.yml
drupal_base_url: http://example_hostname.com

# CONVERT CONTENTFUL MODEL TO CONTENTFUL IMPORT STRUCTURE
content_model_json: PATH_TO_CONTENTFUL_MODEL_JSON_FILE/contentful_model.json
converted_model_dir: PATH_WHERE_CONVERTED_CONTENT_MODEL_WILL_BE_SAVED/contentful_structure.json

contentful_structure_dir: PATH_TO_CONTENTFUL_STRUCTURE_JSON_FILE/contentful_structure.json